# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New Features and Improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
  - title: 🛡️ Security
    labels:
      - security
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: 📦 Dependency Updates
    labels:
      - dependencies
    collapse-after: 5
  - title: ✍️ Other Changes
  # Default label used by Dependabot

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog

version-resolver:
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

autolabeler:
  - label: bug
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: 'has-frontend'
    files:
      - '*.js'
      - '*.ts'
      - '*.vue'
