# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

no-changes-template: '### No changes'

template: $CHANGES

categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: 🚀 New Features and Improvements
    labels:
      - enhancement
      - feature
  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
  - title: 🛡️ Security
    labels:
      - security
  - title: 👻 Maintenance
    labels:
      - chore
      - internal
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
      - tests
  - title: 📦 Dependency Updates
    labels:
      - dependencies
    collapse-after: 5
  - title: ✍️ Other Changes

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

autolabeler:
  - label: bug
    branch:
      - '/fix\/.+/'
      - '/bugfix\/.+/'
      - '/hotfix\/.+/'
  - label: enhancement
    branch:
      - '/feature\/.+/'
  - label: has-frontend
    files:
      - '*.js'
      - '*.ts'
      - '*.vue'
  - label: has-migration
    files:
      - 'migrations/*'
