# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
name-template: 'v$RESOLVED_VERSION'

tag-template: 'v$RESOLVED_VERSION'

no-changes-template: '### No changes'

template: $CHANGES

categories:
  - title: ✨ Features
    labels:
      - feature  
  - title: 🛠️ Improvements
    labels:
      - improvement
  - title: 🐛 Bug Fixes
    labels:
      - bugfix  
  - title: 📁 Has migrations
    labels:
      - has-migration

exclude-labels:
  - linting
  - reverted
  - no-changelog
  - skip-changelog

version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
  patch:
    labels:
      - patch
  default: patch

autolabeler:
  - label: bug
    branch:
      - '/bugfix\/.+/'
  - label: feature
    branch:
      - '/feature\/.+/'
  - label: improvement
    branch:
      - '/improvement\/.+/'
  - label: has-frontend
    files:
      - '*.js'
      - '*.ts'
      - '*.vue'
  - label: has-migration
    files:
      - 'migrations/*'
