name: Create GitHub Release

on:
  workflow_call:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Release Configuration
        run: gh api repos/tectonic/.github/contents/.github/release.yml | jq -r '.content' | base64 -d > .github/release.yml

      - name: Display structure of downloaded files
        run: git status

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
