name: Create GitHub Release

on:
  workflow_call:

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
