name: Create GitHub Release

on:
  workflow_call:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Release Configuration
        id: fetch-config
        run: |
          OUTPUT=$(gh api repos/tectonic/.github/contents/.github/release.yml | jq -r '.content' | base64 -d)
          echo "$OUTPUT" > .github/release.yml
          echo "::set-output name=fetch-output::$OUTPUT"
      
      - name: Print Fetch Output
        run: echo "${{ steps.fetch-config.outputs.fetch-output }}"

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
