name: Create GitHub Release

on:
  workflow_call:

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Shared Release Configuration
        uses: actions/download-artifact@v4
        with:
          name: .github/release.yml
          path: .github
          repository: tectonic/.github

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
