name: Draft Release

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  draft_release:
    name: ""

    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
