name: "Notify Slack Release"

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
        description: "Slack webhook URL for release notifications"

jobs:
  notify:
    name: "Send Notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Get Latest Release"
        id: latest-release
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            return {
              repo: context.repo.repo,
              tag: release.data.tag_name,
              body: release.data.body,
              url: release.data.html_url
            };

      - name: "Send Slack Notification"
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚀 ${{ fromJSON(steps.latest-release.outputs.result).repo }} ${{ fromJSON(steps.latest-release.outputs.result).tag }} released!"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Check out the release notes <${{ fromJSON(steps.latest-release.outputs.result).url }}|here>."
                  }
                }
              ]
            }
