name: Release Drafter

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
